"use client";

import { useRef, useState } from "react";
import type { GameStarted, RevealView, RoomView, SelfView } from "@wahala/shared";

const beats = ["The Accusations", "The Truth", "The Receipts"] as const;
function majorityLabel(options: { id: string; label: string }[], counts: Record<string, number>) {
  return options.find(o => (counts[o.id] ?? 0) >= 3)?.label ?? "Unresolved — no three-of-five majority";
}
function Tallies({ label, options, counts }: { label: string; options: { id: string; label: string }[]; counts: Record<string, number> }) {
  const total = options.reduce((sum, o) => sum + (counts[o.id] ?? 0), 0);
  return <section aria-label={`${label} tallies`} className="rounded-2xl border border-divider bg-surface p-4"><h3 className="font-bold">{label}</h3><ul className="mt-4 space-y-4">{options.map(o => <li key={o.id}><div className="flex justify-between gap-4 text-sm"><span>{o.label}</span><span className="shrink-0 font-mono text-gold">{counts[o.id] ?? 0}/5</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-raised" aria-hidden="true"><div className="h-full rounded-full bg-gold" style={{ width: `${(counts[o.id] ?? 0) * 20}%` }} /></div></li>)}</ul><p className="mt-4 text-xs text-muted">{5 - total} abstention{5 - total === 1 ? "" : "s"} · {majorityLabel(options, counts)}</p></section>;
}

export default function Reveal({ room, self, started, reveal }: { room: RoomView; self: SelfView; started: GameStarted | null; reveal: RevealView }) {
  const [beat, setBeat] = useState(0);
  const heading = useRef<HTMLHeadingElement>(null);
  const name = (id: string) => started?.cast.find(p => p.participantId === id)?.displayName ?? room.participants.find(p => p.participantId === id)?.nickname ?? "Participant";
  const personaName = (personaId: string) => started?.cast.find(p => p.personaId === personaId)?.displayName ?? personaId;
  function show(next: number) {
    setBeat(next);
    heading.current?.focus();
    heading.current?.scrollIntoView({ block: "start", behavior: "instant" });
  }
  const actions = room.publicEvents.filter(e => ["EXPOSE", "CONFRONT", "DEFEND", "ANSWER", "REFUSE"].includes(e.kind));
  return <section aria-labelledby="reveal-heading" className="space-y-6">
    <div className="flex items-center justify-between gap-3"><p className="eyebrow">The Big Reveal · {beat + 1} / 3</p>{beat < 2 && <button className="text-xs text-muted underline underline-offset-4" onClick={() => show(2)}>Skip to receipts</button>}</div>
    <h1 ref={heading} tabIndex={-1} id="reveal-heading" className="text-4xl font-bold leading-tight outline-none">{beats[beat]}</h1>
    <nav aria-label="Reveal chapters" className="grid grid-cols-3 gap-2">{beats.map((title, index) => <button key={title} aria-current={beat === index ? "step" : undefined} className={`tab-button border text-xs ${beat === index ? "border-gold bg-gold/10 text-gold" : "border-divider text-muted"}`} onClick={() => show(index)}>{index + 1}. {title.replace("The ", "")}</button>)}</nav>
    <div key={beat} className="reveal-beat space-y-5">
      {beat === 0 && <><p className="text-muted">What the group believed. Each category stands on its own; fewer than three votes leaves it unresolved.</p><Tallies label="Cause" options={room.causeOptions} counts={reveal.tallies.causes} /><Tallies label="Principal participant" options={room.participants.map(p => ({ id: p.participantId, label: name(p.participantId) }))} counts={reveal.tallies.actors} /><Tallies label="Resolution" options={room.resolutionOptions} counts={reveal.tallies.resolutions} /><button className="primary-button w-full" onClick={() => show(1)}>Uncover the truth</button></>}
      {beat === 1 && <><p className="text-muted">The locked case truth. Every character held only part of the story.</p><article className="secret-card rounded-2xl border border-coral/60 bg-surface p-6"><p className="eyebrow text-coral">The principal actor</p><h2 className="mt-4 text-5xl font-black" data-testid="revealed-actor">{name(reveal.correct.principalActorParticipantId)}</h2><dl className="mt-6 space-y-5"><div><dt className="text-xs uppercase tracking-wider text-muted">What caused it</dt><dd className="mt-2 text-lg font-semibold">{room.causeOptions.find(o => o.id === reveal.correct.causeId)?.label}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted">The viable resolution</dt><dd className="mt-2 text-lg font-semibold">{room.resolutionOptions.find(o => o.id === reveal.correct.resolutionId)?.label}</dd></div></dl><p className="mt-6 text-sm leading-relaxed" data-testid="reveal-summary">{reveal.summary}</p></article><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border border-divider bg-surface p-4"><p className="text-xs text-muted">Cause + resolution</p><p className={`mt-2 font-bold ${reveal.groupSuccess ? "text-mint" : "text-coral"}`}>{reveal.groupSuccess ? "Group success" : "Group objective missed"}</p></div><div className="rounded-xl border border-divider bg-surface p-4"><p className="text-xs text-muted">Principal actor</p><p className={`mt-2 font-bold ${reveal.actorIdentified ? "text-mint" : "text-coral"}`}>{reveal.actorIdentified ? "Identified" : "Not identified"}</p></div></div><button className="primary-button w-full" onClick={() => show(2)}>Follow the receipts</button></>}
      {beat === 2 && <><p className="text-muted">The Wahala Chain, in chronological order. Public player claims are shown separately from the canonical facts.</p><ol aria-label="Canonical timeline" className="space-y-5 border-l border-gold/40 pl-5">{reveal.chain.map((event, index) => <li key={`${event.minute}:${index}`}><p className="font-mono text-sm text-gold">{event.minute} · {personaName(event.personaId)}</p><p className="mt-2 text-sm leading-relaxed">{event.truth}</p></li>)}</ol><section aria-label="Important public actions" className="rounded-2xl border border-divider bg-surface p-4"><h2 className="text-xl font-bold">What happened in the room</h2>{actions.length ? <ol className="mt-4 space-y-4">{actions.map(event => <li key={event.id}><p className="text-xs text-gold">{event.fromParticipantId ? name(event.fromParticipantId) : "Case update"} · {event.kind === "EXPOSE" ? "Published verified receipt" : "Player claim / response"}</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{event.text}</p></li>)}</ol> : <p className="mt-3 text-sm text-muted">No public challenges or receipts were submitted in this case.</p>}</section><section aria-label="Mission outcomes" className="space-y-3"><h2 className="text-xl font-bold">Everybody had a mission</h2>{reveal.missions.map(mission => <article key={mission.participantId} className={`rounded-xl border bg-surface p-4 ${mission.participantId === self.participantId ? "border-gold/50" : "border-divider"}`}><div className="flex justify-between gap-4"><h3 className="font-bold">{personaName(mission.personaId)}{mission.participantId === self.participantId ? " (you)" : ""}</h3><span className={`shrink-0 text-sm ${mission.success ? "text-mint" : "text-coral"}`}>{mission.success ? "Achieved" : "Not achieved"}</span></div><p className="mt-2 text-sm text-muted">{mission.missionDescription}</p></article>)}</section><details className="rounded-xl border border-divider bg-surface p-4"><summary className="cursor-pointer font-semibold">Your memory gaps</summary><p className="mt-3 text-sm">{self.startingMemory}</p>{self.midgameMemory && <p className="mt-3 text-sm">{self.midgameMemory}</p>}{self.myMemoryFragments.map(e => <p key={e.id} className="mt-3 text-sm text-mint">✓ {e.body}</p>)}</details><p role="status" className="text-center text-sm text-muted">Case complete. You can revisit every chapter.</p></>}
    </div>
    <p className="text-xs text-muted">Casual match · {room.aiPresenceDisclosure === "HUMANS_ONLY" ? "Humans only" : "AI-controlled characters may participate"}</p>
  </section>;
}
